### PR TITLE
fix(excel import): improved error messages shown in excel formula information

### LINKED ISSUE #1034: [Bug] Error in Excel Formula Information leads to non-understandable errror description to the user
## Description

Errors / Warnings in Formula parsing result in a non-differentiating error message. I checked the docs of the evaluateAll functionality and there is non specified. It seems to be thrown at [this point](https://github.com/eclipse-tractusx/puris/blob/main/backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java#L138).

## Current behaviour

We introduced the formula evaluation (pr #1020, we actually stumbled about the error but didn't notice the message) and [noted down non-working formulas in the docs](https://github.com/eclipse-tractusx/puris/blob/main/docs/user/User_Guide.md#formula-support) per link (e.g. UNIQUE). The error message provided is not very helpful as it's generic:

Image

This file produces such an error: 

[stock-template-error-unique.xlsx](https://github.com/user-attachments/files/23113672/stock-template-error-unique.xlsx)

## Expected behavior

The logged warning message would have helped me to identify the issue easier. 

## Steps to reproduce the Bug

1. Deploy via `./deploy.sh -ci`
2. Login to supplier
3. Import the attached excel template

appVersion: 4.1.0

### PR DESCRIPTION
**Pull request by OlgaIvkovic**
improved error messages shown in excel formula information for excel import

- Formula evaluation on excel import now provides error messages more understandable to the user 

## Description

Fixes #1034 
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [ ] If helm chart has been changed, the chart version has been bumped to either next major, minor or patch level (compared to released chart).

### CODE REVIEW

File: backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java [hunk 1]
```diff
@@ -763,4 +768,61 @@ private boolean isRowEmpty(Row row) {
...
+                for (Row row : sheet) {
+                    for (Cell cell : row) {
+                        if (cell != null && cell.getCellType() == CellType.FORMULA) {
+                            try {
+                                evaluator.evaluateFormulaCell(cell);
+                            } catch (RuntimeException ex) {
+                                if (ex.getCause() instanceof NotImplementedFunctionException){
+                                    log.error("Runtime Exception is notImplementedFunction");
+                                }
+                                log.error("RUntime exception cause is: " + ex.getCause().toString());
```
Comment (tom-rm-meyer-ISST) [inline backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java]: Sorry for the misunderstanding. The snippet has only been meant as an example for catching the inner cause. Please implement the triple check (else-ifs / switch) on `NotImplementedFunctionException`, `FormulaParseException` and a fallback, same as before. The error messages were much better!

File: backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java [hunk 2]
```diff
@@ -785,11 +785,22 @@ private List<DataImportError> evaluateWorkbook(Workbook workbook) {
...
+                                    case FormulaParseException fpe -> {
+                                        errors.add(new DataImportError(rowIndex, List.of(String.format("Formula parse error at Sheet '%s'!%s. Formula: =%s. Reason: %s", sheetName, cellRef, formula, nullToEmpty(fpe.getMessage())))));
+                                    }
+                                    default -> {
+                                        errors.add(new DataImportError(rowIndex, List.of(String.format("Error evaluating at Sheet '%s'!%s. Formula: =%s. Reason: %s", sheetName, cellRef, formula, nullToEmpty(ex.getMessage())))));
+                                    }
                                 }
-                                log.error("RUntime exception cause is: " + ex.getCause().toString());
-                                errors.add(new DataImportError((cell.getRowIndex() + 1), List.of(String.format("Error evaluating at Sheet '%s'!%s. Formula: =%s. Reason: %s", sheetName, new CellReference(cell).formatAsString(), getFormulaAsString(cell), nullToEmpty(ex.getMessage())))));
+                                log.error("RUntime exception cause is: " + cause.toString());
```
Comment (tom-rm-meyer-ISST) [inline backend/src/main/java/org/eclipse/tractusx/puris/backend/file/logic/service/ExcelService.java]:
```suggestion
                                log.error("Excel import failed due to RuntimeException with cause: " + cause.toString());
```

typo. If we log it, we can directly make it more precise. If we can add a filename or similar (easily) would be even better.

**Comment by OlgaIvkovic** [comment]
Hi Tom! The check kept failing so I decided to revert the changes with the file name, hope that's okay

**Review by tom-rm-meyer-ISST — APPROVED** [review]
LGTM, thanks for iterating over this with me!

Yeah, user inputs with CodeQl are tedious. Feel free to discuss these with me. We use the PatternStore non-whitespace or whitespace related pattern in the controllers. On Service Level the check still raises vulnerabilities, but IMHO this is false positive!
