### PR TITLE
Fix/days of supply calculation

### LINKED ISSUE #771: Resolve Todo for optional partnerBpnl
## Description

During merge of #769 we noticed that changes from #694 have not been considered. Method SupplyService.calculateDaysOfSupply may have issues regarding partner of value null when opening the dashboard.

## Current behaviour

Method takes optional partnerBpnl but it's mandatory for supply (not null annotation). Please check how to handle / assert case.

I implemented the partnerBpnl assuming it's not null. This causes the MaterialListView to generate an error as it want's to calculate the days of supply without partner.

## Expected behavior

Resolve / analyze todo. Likely it's nothing.

### PR DESCRIPTION
**Pull request by ReneSchroederLJ**
## Description

- adjusted the calculation of days of supply to be in line with the standard
- notable differences are:
    - actual item stock is displayed on the previous day
    - days of supply compares the current stock in a day to demands/outgoing shipments of the upcoming days
    - incoming deliveries/production are not included in the calculation for a single day
-  a unit test for the calculation was provided
    - the test uses the sample data provided in the [standard document](https://catenax-ev.github.io/docs/next/standards/CX-0145-DaysofsupplyExchange#522-process-representation)
    - **note:** There seems to be a mistake in the standard data. the days of supply for day 5 should be 0

resolves #771 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
- [x] If helm chart has been changed, the chart version has been bumped to either next major, minor or patch level (compared to released chart).

### CODE REVIEW

File: backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/SupplyService.java [hunk 1]
```diff
@@ -90,31 +87,30 @@ public final void deleteReportedSupply(TReported entity) {
...
 
             T supply = createSupplyInstance();
             supply.setMaterial(materialService.findByOwnMaterialNumber(material));
             supply.setDate(date);
             supply.setDaysOfSupply(daysOfSupply);
-            // TODO rene: see above
             if (partner != null){
                 supply.setPartner(partner);
             };
             supplyList.add(supply);
```
Comment (tom-rm-meyer-ISST) [inline backend/src/main/java/org/eclipse/tractusx/puris/backend/supply/logic/service/SupplyService.java:113]: Please remove duplicate empty line

File: backend/src/test/java/org/eclipse/tractusx/puris/backend/supply/logic/SupplyServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+            6
+        )).thenReturn(deliveryQuantities);
+
+        when(reportedDeliveryService.getQuantityForDays(
+            TEST_MATERIAL.getOwnMaterialNumber(),
+            Optional.of(BPNL_SUPPLIER),
+            Optional.empty(),
+            DirectionCharacteristic.INBOUND,
+            6
+        )).thenReturn(List.of(0.0, 0.0, 0.0, 0.0, 0.0, 0.0));
```
Comment (tom-rm-meyer-ISST) [inline backend/src/test/java/org/eclipse/tractusx/puris/backend/supply/logic/SupplyServiceTest.java:141]: minor: please move this up as variable `reportedDeliveryQuantities` (just for constistency)

**Review by tom-rm-meyer-ISST — CHANGES_REQUESTED** [review]
Thanks a lot for the fast fix! Had smaller findings. Please check.

**Review by tom-rm-meyer-ISST — APPROVED** [review]
LGTM, thanks a lot!
